vich_uploader:
    db_driver: orm

    mappings:
       post_images:
           uri_prefix: /images/posts
           upload_destination: '%kernel.project_dir%/public/images/posts'
       post_audios:
           uri_prefix: /audios/posts
           upload_destination: '%kernel.project_dir%/public/audios/posts'
       slide_images:
           uri_prefix: /images/slides
           upload_destination: '%kernel.project_dir%/public/images/slides'

parameters:
    app.path.post_images: /uploads/images/posts
    app.path.post_audios: /uploads/audios/posts
    app.path.slide_images: /uploads/images/slides