machine:
  php:
    version: 7.0.0RC7
  ruby:
    version: 2.0.0-p481

dependencies:
  override:
    - composer install --prefer-source --no-interaction --no-scripts
    - cp app/config/parameters_test.circle.yml app/config/parameters_test.yml
    - app/console doctrine:database:drop --env=test --no-interaction --force
    - app/console doctrine:database:create --env=test --no-interaction
    - app/console doctrine:schema:update --env=test --no-interaction  --force
    - app/console doctrine:fixtures:load --env=test --no-interaction
    - php app/console asset:install --env=test --no-interaction
    - php app/console assetic:dump --env=test --no-interaction
  post:
    - rvm use 2.0.0-p481 do gem install psych
    - gem install capifony

test:
  override:
    - SYMFONY_DEPRECATIONS_HELPER="weak" phpunit -c app/

deployment:
  production:
    branch: master
    commands:
      - cap -S revision=$CIRCLE_SHA1 deploy